amend! ci(GHA): Add build script for x64, arm64
ci(GHA): Add build script for x64, arm64

Co-authored-by: mstv@gmx.net

diff --git a/.github/workflows/ge-build.yml b/.github/workflows/ge-build.yml
--- a/.github/workflows/ge-build.yml
+++ b/.github/workflows/ge-build.yml
@@ -2,30 +2,21 @@ name: GitExtensions Build (x64, arm64)
 
 on:
   pull_request:
-    branches: [ master ]
+    branches: [ master, release/* ]
   push:
-    branches: [ master ]
-  # Manually triggered via the Actions UI, with inputs
-  workflow_dispatch:
-    inputs:
-      ge-release-version:
-        description: "GE release version"
-        required: true
-        type: string
-        default: '33.33.33' # for dev
-      run-x64-tests:
-        description: "Run tests for x64 build"
-        type: boolean
-        default: true
-      run-arm64-tests:
-        description: "Run tests for arm64 build"
-        type: boolean
-        default: false # skip arm64 test by default, as it doesn't complete, resulting in timeout...
+    branches: [ master, release/* ]
 
 env:
-  # version is '33.33.33' for PR/push, or take it from user's input when manually triggered,
-  # then append the current run number
-  ge-version: ${{ github.event_name == 'workflow_dispatch' && inputs.ge-release-version || '33.33.33' }}.${{ github.run_number }}
+  # GE release version
+  ge-release-version: '6.0.5'
+  # Run tests for x64 build
+  run-x64-tests: false # TODO: turn on again when signing works - and when TC GetOriginalLineInPreviousCommit passes stably
+  # Run tests for arm64 build
+  run-arm64-tests: false # skip arm64 test by default, as ThemeModule relies on GetGitExtensionsFullPath (TODO: 'C:\Program Files\dotnet\Themes'), and as test doesn't complete, resulting in timeout...
+  # Disable the .NET logo in the console output.
+  DOTNET_NOLOGO: true
+  # Disable the .NET first time experience to skip caching NuGet packages and speed up the build.
+  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
 
 jobs:
   build:
@@ -38,9 +29,12 @@ jobs:
         dotnet-version: [ 9.0.x ]
 
     runs-on: ${{ matrix.os }}
-    timeout-minutes: 60
+    timeout-minutes: 30
 
     steps:
+      - name: Append the current run number
+        run: echo "ge_version=${{ env.ge-release-version }}.${{ github.run_number }}" >> $env:GITHUB_ENV
+
       - name: Checkout
         uses: actions/checkout@v5
 
@@ -60,28 +54,30 @@ jobs:
       - name: Install WiX
         run: dotnet tool install --global wix
 
+      - name: Mark the repo as clean
+        run: .\eng\Mark-RepoClean.ps1      
+
       - name: Set up common build arguments
         run: |
           $buildArgs = '/p:ContinuousIntegrationBuild=true'
           echo "buildArgs=$buildArgs" >> $env:GITHUB_ENV
           $nativeBuildArgs = '/p:VSWherePath="C:\Program Files (x86)\Microsoft Visual Studio\Installer"'
           echo "nativeBuildArgs=$nativeBuildArgs" >> $env:GITHUB_ENV
-          echo "geVersionText=${{ env.ge-version }}" >> $env:GITHUB_ENV
+          echo "geVersionText=$env:ge_version" >> $env:GITHUB_ENV
 
       - name: Set up extra build arguments for PR
         if: github.event_name == 'pull_request'
         run: |
           $shortSha = $(git rev-parse --short ${{ github.event.pull_request.head.sha }})
-          $buildArgs = $env:buildArgs
-          $buildArgs += " /p:GitCommit=$shortSha /p:GitSha=${{ github.event.pull_request.head.sha }}"
+          $buildArgs = "$env:buildArgs /p:GitCommit=$shortSha /p:GitSha=${{ github.event.pull_request.head.sha }}"
           echo "buildArgs=$buildArgs" >> $env:GITHUB_ENV
 
-      - name: Set up extra build arguments for Arm64
+      - name: Set up extra build arguments for arm64
         if: runner.arch == 'arm64'
         run: |
-          $buildArgs = "$env:buildArgs /p:TargetPlatform=arm64"
+          $buildArgs = "/p:TargetPlatform=arm64 $env:buildArgs"
           echo "buildArgs=$buildArgs" >> $env:GITHUB_ENV
-          $nativeBuildArgs = "/p:TargetPlatform=arm64 $env:nativeBuildArgs"
+          $nativeBuildArgs = "/p:TargetPlatform=arm64 $env:nativeBuildArgs" # TargetPlatform must be specified first here because native build fails otherwise
           echo "nativeBuildArgs=$nativeBuildArgs" >> $env:GITHUB_ENV
           $geVersionText = "${env:geVersionText}-arm64"
           echo "geVersionText=$geVersionText" >> $env:GITHUB_ENV
@@ -89,16 +85,16 @@ jobs:
       - name: Set up GE version
         run: |
           cd eng
-          python set_version_to.py -v ${{ env.ge-version }} -t $env:geVersionText
+          python set_version_to.py -v $env:ge_version -t $env:geVersionText
           cd ..
 
       - name: Build GE native components
         run: |
-          dotnet build .\src\native\build.proj -c Release --verbosity q --nologo $env:nativeBuildArgs
+          dotnet build .\src\native\build.proj -c Release --verbosity q $env:nativeBuildArgs
 
       - name: Build GE app
         run: |
-          dotnet build -c Release --verbosity q --nologo $env:buildArgs
+          dotnet build -c Release --verbosity q $env:buildArgs
           # We are done with the build, reset all pending changes
           git reset --hard HEAD
 
@@ -106,40 +102,71 @@ jobs:
         run: |
           # Verify that new strings (if any) have been processed and ready for localisation
           Push-Location .\src\app\GitExtensions
-          dotnet msbuild /p:Configuration=Release /t:_UpdateEnglishTranslations /p:RunTranslationApp=true /p:ContinuousIntegrationBuild=true /v:m
+          dotnet msbuild /p:Configuration=Release /t:_UpdateEnglishTranslations /p:RunTranslationApp=true $env:buildArgs /v:m
           Pop-Location
 
-      - name: Test - for PR/push (but skip arm64 tests by default)
-        id: pr_push_test
-        if: github.event_name != 'workflow_dispatch' && runner.arch != 'arm64'
-        run: dotnet test -c Release --no-restore --no-build --verbosity m --test-adapter-path:. --logger:trx /bl:.\artifacts\log\tests.binlog
-
-      - name: Test - when manually triggered
-        id: dispatched_test
-        if: github.event_name == 'workflow_dispatch' && ((runner.arch == 'arm64' && inputs.run-arm64-tests) || (runner.arch == 'x64' && inputs.run-x64-tests))
-        run: dotnet test -c Release --no-restore --no-build --verbosity m --test-adapter-path:. --logger:trx /bl:.\artifacts\log\tests.binlog
+      - name: Test
+        id:   test
+        if: (runner.arch == 'arm64' && env.run-arm64-tests == 'true') || (runner.arch == 'x64' && env.run-x64-tests == 'true')
+        run: dotnet test -c Release --no-restore --no-build $env:buildArgs --verbosity m --test-adapter-path:. --logger:trx /bl:.\artifacts\log\tests.binlog
 
       - name: Upload test logs if test failure
-        if: failure() && (steps.pr_push_test.conclusion == 'failure' || steps.dispatched_test.conclusion == 'failure')
-        uses: actions/upload-artifact@v4
+        if: failure() && steps.test.conclusion == 'failure'
+        uses: actions/upload-artifact@v6
         with:
-          name: FailedTestLogs-v${{ env.ge-version }}-${{ runner.arch }}
+          name: FailedTestLogs-v${{ env.ge_version }}-${{ runner.arch }}
           path: |
             artifacts/log/tests.binlog
             artifacts/Release/TestsResults/*.trx
-          retention-days: 7
+          retention-days: 31
 
       - name: Package GE app for deployment
         run: |
-          dotnet publish -c Release --no-build $env:buildArgs
+          $platformArg = '/p:TargetPlatform=${{ runner.arch }}'.ToLower()
+          dotnet publish -c Release --no-build $platformArg
 
-      - name: Upload GE distribution files - when manually triggered
-        if: github.event_name == 'workflow_dispatch'
-        uses: actions/upload-artifact@v4
+      - name: Display artifacts
+        run: ls -R artifacts/Release/publish/
+
+      - name: Upload GE distribution files
+        uses: actions/upload-artifact@v6
         with:
-          name: GE-v${{ env.ge-version }}-${{ runner.arch }}-dist
+          name: GE-v${{ env.ge_version }}-${{ runner.arch }}-dist
           path: |
             artifacts/Release/publish/*.msi
             artifacts/Release/publish/*.zip
+
+  trigger-signing:
+    name: Upload dist files to SignPath
+    runs-on: ubuntu-latest
+    needs: build
+    if: ${{ success() && vars.ARTIFACT_SIGNING_ENABLED == 'true' }}
+    steps:
+      - name: Download build artifacts
+        uses: actions/download-artifact@v7
+        with:
+          path: ./artifacts
+          merge-multiple: true
+
+      - name: Display artifacts
+        run: ls -R ./artifacts
+
+      - name: Upload unsigned artifacts
+        id:   upload-unsigned-artifacts
+        uses: actions/upload-artifact@v6
+        with:
+          name: GE-v${{ env.ge-release-version }}.${{ github.run_number }}-unsigned
+          path: ./artifacts/*
           retention-days: 7
 
+      - name: Submit signing request to SignPath
+        if: false # TODO: turn on when SignPath has adapted the GE GH URL
+        uses: SignPath/github-action-submit-signing-request@v1
+        with:
+          connector-url: https://githubactions.connectors.signpath.io
+          api-token: ${{ secrets.SIGNPATH_API_TOKEN }}
+          organization-id: "7c19b2cf-90f7-4d15-9b12-1b615f7c18c4"
+          project-slug: "GitExtensions_combined"
+          signing-policy-slug: "release-2020"
+          github-artifact-id: ${{ steps.upload-unsigned-artifacts.outputs.artifact-id }}
+          wait-for-completion: false
